// Import Next.js Metadata type for defining page metadata
import type { Metadata } from "next";
// Import Geist and Geist Mono fonts from Google's font library for consistent typography
import { Geist, Geist_Mono } from "next/font/google";
// Import global CSS styles applied across the application
import "./globals.css";

// Configure Geist Sans font with Latin subset and CSS variable for use in styling
const geistSans = Geist({
  variable: "--font-geist-sans", // Custom CSS variable for font-family
  subsets: ["latin"], // Restrict to Latin characters for performance
});

// Configure Geist Mono font for code or monospaced text, with Latin subset
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Custom CSS variable for monospaced font
  subsets: ["latin"], // Restrict to Latin characters for performance
});

// Define metadata for the application (used for SEO and browser display)
export const metadata: Metadata = {
  title: "Create Next App", // Default title; update to reflect actual app name
  description: "Generated by create next app", // Default description; customize for specific app purpose
};

// Root layout component that wraps all pages in the Next.js app
export default function RootLayout({
  children, // React children (page content) to be rendered within the layout
}: Readonly<{
  children: React.ReactNode; // Type definition for children prop
}>) {
  return (
    // Set HTML language to English for accessibility and SEO
    <html lang="en">
      <body
        // Apply both Geist Sans and Mono fonts as CSS variables, with antialiasing for smoother rendering
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} {/* Render page-specific content here */}
      </body>
    </html>
  );
}
